In [1]:
import pandas as pd

df = pd.DataFrame({
    'fruit': ['Apple', 'Banana'],
    'Monday': [10, 20],
    'Tuesday': [15, 25]
})

df

    fruit  Monday  Tuesday
0   Apple      10       15
1  Banana      20       25

In [ ]:
#first separate the column/columns you are keeping
piece = df[['fruit']].copy()

#create the column name you want and make every row Monday
piece['day'] = 'Monday'

#Create a new column called sales and fills every row with 'Monday' values.
piece['sales'] = df['Monday'].values

#now repeat for other days

piece2 = df[['fruit']].copy()

piece2['day'] = 'Tuesday'

piece2['sales'] = df['Tuesday'].values

final_data = pd.concat([piece, piece2], ignore_index=True)
final_data

    fruit      day  sales
0   Apple   Monday     10
1  Banana   Monday     20
2   Apple  Tuesday     15
3  Banana  Tuesday     25